nix: Update expected SHA for riscv-semihosting
riscv-semihosting branch that we are dependent on has moved and so we need to
update hubris.nix as well to update the expected SHA. The way to update this
was:

1. Run `nix flake check` and let it fail with an error message like:
```
error: hash mismatch in fixed-output derivation '/nix/store/b1bp8zff3d1yamw0rc4vsdzvc0mc8izz-riscv-semihosting-ec93c72.drv':
specified: sha256-JzQyv2/4F1FBclFZUsIOJ1TREaBIKQp/TOZhBSHyQGY=
got: sha256-sGa++ywE9kYw9VnPKeYyzaRJsYOzF0mNE7C9c2TdUNQ=
```

2. Use the "got" sha to update hubrix.nix entry for riscv-semihosting

3. Re-run `nix flake check` to ensure it succeeds now.

Currently, I do not know of a better way to update this.